
export const assignments = [
    {"name": "Project Proposal", "description": "The problem space and applications, example scenarios, related technology, potential design solutions, resources needed, and what the final demo will entail."},
    {"name": "Project Requirements Document", "description": "Details the various aspects of project. Including a one paragraph summary of the project, deliverables, critical features, performance metrics, milestones, responsibilities of each team member, materials and outside help needed, budget, risks, and how risks will be addressed."},
    {"name": "Rapid Prototypes", "description": "To visualize and convey project concepts using low fidelity techniques like sketches, slides, paper mockups, foam mockups, etc."},
    {"name": "Project Status Presentions", "link": "https://docs.google.com/presentation/d/e/2PACX-1vT4LfO55XvPWm9LhyCZEHLfZwjXiLFziqfEQ9FI42E6PKGDW8jZdZ7dNHaN7tUDHmr4VqQ7NdDmMXTD/pub?start=false&loop=false&delayms=3000&slide=id.g310119febc9_0_30", "description": "Current state of the project, biggest remaining challenges, and a high-level overview of system architecture."},
    {"name": "Kickstarter-style Website", "description": "A public page given to potential customers and investors. Explains what your product is, what value it has to offer, features, and specifications."},
    {"name": "Final Technical Report", "description": "Encapsulates the work for the entire quarter as a technical design document. Provides details on design decisions, details of the implementation itself, test and evaluation results to prove design/implementation works, provide schematics and block diagrams to support the discussion, discuss the societal/ethical consideration of the work, and discuss future work and areas that need improvement."},
]
